name: Build and Deploy Nuxt 3 to Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21' 

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4 : Builder le projet Nuxt
    - name: Build the project
      run: npm run build

    # Étape 5 : Préparer les fichiers buildés
    - name: Prepare built files
      run: |
        mkdir build-output
        cp -r .output/public/* build-output/
        tar -czf build-output.tar.gz -C build-output .

    # Étape 6 : Obtenir l'URL d'upload depuis Pterodactyl
    - name: Get upload URL from Pterodactyl
      env:
        PTERODACTYL_PANEL_URL: ${{ secrets.PTERODACTYL_PANEL_URL }}
        PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
        PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }}
      run: |
        echo "Récupération de l'URL d'upload..."
        UPLOAD_URL_RESPONSE=$(curl -s -X GET \
          "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/files/upload" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $PTERODACTYL_API_KEY")

        echo "Réponse brute : $UPLOAD_URL_RESPONSE"

        UPLOAD_URL=$(echo "$UPLOAD_URL_RESPONSE" | grep -o '"url":"[^"]*' | grep -o '[^"]*$')
        if [ -z "$UPLOAD_URL" ]; then
          echo "Erreur : Impossible d'obtenir l'URL d'upload."
          exit 1
        fi
        echo "URL d'upload obtenue : $UPLOAD_URL"

    # Étape 7 : Uploader les fichiers buildés
    - name: Upload built files to Pterodactyl
      env:
        UPLOAD_URL: ${{ steps.get-upload-url.outputs.UPLOAD_URL }}
      run: |
        echo "Upload des fichiers buildés..."
        curl -s -X POST "$UPLOAD_URL" \
          -F "file=@build-output.tar.gz"
        echo "Upload terminé."

    # Étape 8 : Redémarrer le serveur
    - name: Restart server
      env:
        PTERODACTYL_PANEL_URL: ${{ secrets.PTERODACTYL_PANEL_URL }}
        PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
        PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }}
      run: |
        echo "Redémarrage du serveur..."
        curl -X POST \
          "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/power" \
          -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{ "signal": "restart" }'
        echo "Serveur redémarré avec succès."