name: Deploy to Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt application
        run: npm run build 

      - name: Archive production artifacts
        run: tar -czvf release.tar.gz .output 
      - name: Deploy to Pterodactyl
        env:
          PTERODACTYL_PANEL_URL: ${{ secrets.PTERODACTYL_PANEL_URL }} 
          PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}    
          PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }} 
        run: |
          # Vérifier que les variables d'environnement sont définies
          if [ -z "$PTERODACTYL_PANEL_URL" ] || [ -z "$PTERODACTYL_API_KEY" ] || [ -z "$PTERODACTYL_SERVER_ID" ]; then
            echo "Erreur : Les secrets PTERODACTYL_PANEL_URL, PTERODACTYL_API_KEY, ou PTERODACTYL_SERVER_ID ne sont pas configurés."
            exit 1
          fi

          # 1. Obtenir une URL d'upload sécurisée depuis l'API Pterodactyl
          UPLOAD_URL_RESPONSE=$(curl -s -X GET \
            "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/files/upload" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -H "Accept: application/json")
          
          UPLOAD_URL=$(echo "$UPLOAD_URL_RESPONSE" | grep -o '"url":"[^"]*' | grep -o '[^"]*$')

          if [ -z "$UPLOAD_URL" ]; then
            echo "Erreur : Impossible d'obtenir l'URL d'upload depuis Pterodactyl."
            echo "Réponse de l'API : $UPLOAD_URL_RESPONSE"
            exit 1
          fi
          echo "URL d'upload obtenue : $UPLOAD_URL"

          # 2. Uploader l'archive
          curl -s -X POST \
            "$UPLOAD_URL" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -F "files=@release.tar.gz"
          
          echo "Archive uploadée."

          # 3. Décompresser l'archive sur le serveur (optionnel, dépend de votre egg Pterodactyl)
          # Si votre egg ne décompresse pas automatiquement, vous pourriez avoir besoin d'une étape supplémentaire ici
          # ou de modifier votre egg pour qu'il gère la décompression des .tar.gz
          # Par exemple, pour supprimer l'ancien dossier .output et décompresser :
          # (Cela nécessite que l'API Pterodactyl permette l'exécution de commandes ou la gestion de fichiers de cette manière)
          
          # Supprimer l'ancien dossier .output (s'il existe)
          curl -s -X POST \
            "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/files/delete" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "root": "/",
                  "files": [".output"]
                }'
          echo "Ancien dossier .output supprimé (si existant)."
          
          # Décompresser la nouvelle archive
          curl -s -X POST \
            "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/files/decompress" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "root": "/",
                  "file": "release.tar.gz"
                }'
          echo "Nouvelle archive décompressée."

          # Supprimer l'archive après décompression
           curl -s -X POST \
            "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/files/delete" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "root": "/",
                  "files": ["release.tar.gz"]
                }'
          echo "Archive release.tar.gz supprimée du serveur."

          # 4. Redémarrer le serveur (optionnel, mais souvent nécessaire pour que les changements prennent effet)
          curl -s -X POST \
            "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/power" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{ "signal": "restart" }'
          
          echo "Commande de redémarrage du serveur envoyée."
