name: Build and Deploy to Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Assurez-vous que la version correspond à votre projet

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4 : Builder le projet
    - name: Build the project
      run: npm run build

    # Étape 5 : Copier les fichiers buildés
    - name: Copy built files
      run: |
        mkdir build-output
        cp -r dist/* build-output/  # Remplacez "dist" par le dossier généré par le build
        echo "Build files copied to build-output"

    # Étape 6 : Déployer les fichiers vers le serveur Pterodactyl
    - name: Deploy to Pterodactyl
      env:
        PTERODACTYL_PANEL_URL: ${{ secrets.PTERODACTYL_PANEL_URL }}
        PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
        PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }}
      run: |
        echo "Déploiement des fichiers buildés vers Pterodactyl..."
        UPLOAD_URL_RESPONSE=$(curl -s -X GET \
          "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/files/upload" \
          -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
          -H "Accept: application/json")

        # Extraire l'URL d'upload
        UPLOAD_URL=$(echo "$UPLOAD_URL_RESPONSE" | grep -o '"url":"[^"]*' | grep -o '[^"]*$')
        if [ -z "$UPLOAD_URL" ]; then
          echo "Erreur : Impossible d'obtenir l'URL d'upload."
          exit 1
        fi

        # Uploader les fichiers buildés
        curl -s -X POST "$UPLOAD_URL" \
          -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
          -F "files=@build-output/release.tar.gz"

        echo "Fichiers déployés avec succès !"

    # Étape 7 : Redémarrer le serveur
    - name: Restart server
      env:
        PTERODACTYL_PANEL_URL: ${{ secrets.PTERODACTYL_PANEL_URL }}
        PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
        PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }}
      run: |
        echo "Redémarrage du serveur..."
        curl -X POST \
          "$PTERODACTYL_PANEL_URL/api/client/servers/$PTERODACTYL_SERVER_ID/power" \
          -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{ "signal": "restart" }'
        echo "Serveur redémarré avec succès."